### PR TITLE
Authorization resource required fields

### PR DESCRIPTION
**Pull request by zevisert**
### Description

Updates the `AuthorizationResource.permissions[].resource` schema to match the influx API: https://docs.influxdata.com/influxdb/cloud/api/v2/#operation/PostAuthorizations

### Relations

Relates https://github.com/komminarlabs/pulumi-influxdb/issues/10

### Output from Acceptance Testing

```console
> # zevisert in /code/o/g/ko/terraform-provider-influxdb/ on authorization-resource-required-fields
> make testacc                                                                                                    
TF_ACC=1 go test ./... -v  -timeout 120m
?       github.com/komminarlabs/terraform-provider-influxdb     [no test files]
=== RUN   TestAccAuthorizationDataSource
--- PASS: TestAccAuthorizationDataSource (6.15s)
=== RUN   TestAccAuthorizationResource
--- PASS: TestAccAuthorizationResource (8.71s)
=== RUN   TestAccAuthorizationsDataSource
--- PASS: TestAccAuthorizationsDataSource (3.60s)
=== RUN   TestAccBucketDataSource
--- PASS: TestAccBucketDataSource (3.65s)
=== RUN   TestAccBucketResource
--- PASS: TestAccBucketResource (8.07s)
=== RUN   TestAccBucketsDataSource
--- PASS: TestAccBucketsDataSource (3.64s)
=== RUN   TestAccOrganizationDataSource
--- PASS: TestAccOrganizationDataSource (4.96s)
=== RUN   TestAccOrganizationResource
--- PASS: TestAccOrganizationResource (7.73s)
=== RUN   TestAccOrganizationsDataSource
--- PASS: TestAccOrganizationsDataSource (3.62s)
PASS
ok      github.com/komminarlabs/terraform-provider-influxdb/internal/provider   50.138s
```

### CODE REVIEW

**Comment by thulasirajkomminar** [comment]
@zevisert thanks for your PR. Let me check it out and get back to you.

**Comment by thulasirajkomminar** [comment]
@zevisert I had a look at the API and yes, the attribute `id` & `name` in permissions are optional. But the permissions needs `orgID` even though it is optional in the docs. 

The problem now is if you set `name` attribute the influx api does not send the attribute back in the response causing unexpected new value issue in the provider. You can follow the discussion going on [here](https://discuss.hashicorp.com/t/when-applying-changes-to-provider-produced-an-unexpected-new-value-name-was-cty-stringval-but-now-null/65159/3). I will wait for the response from hashicorp and see how to proceed on this. 

If this is something urgent for you then ofcourse I can set the name attribute read-only for now so you can continue with using `id` attribute. Let me know.

**Comment by zevisert** [comment]
> But the permissions needs orgID even though it is optional in the docs.

From my testing, orgID in _permissions_ is optional at request time, and if it's missing, then the token's required orgID parameter is assumed for the permissions. For example:

```http
POST http://localhost:8086/api/v2/authorizations
Cookie: influxdb-oss-session=a6[...]Iw==
content-type: application/json

{
    "orgID": "90a2dbdc3b0ff490",
    "description": "komminarlabs/terraform-provider-influxdb#22",
    "permissions": [
        { "action": "read",  "resource": { "type": "buckets" } },
        { "action": "write", "resource": { "type": "buckets" } }
    ]
}

--- 
HTTP/1.1 201 Created
Content-Type: application/json; charset=utf-8
X-Influxdb-Build: OSS
X-Influxdb-Version: v2.7.4
Date: Mon, 15 Apr 2024 14:48:13 GMT
Content-Length: 692
Connection: close

{
  "id": "0ce48e112f82f000",
  "token": "Aw4[...]JXQ==",
  "status": "active",
  "description": "komminarlabs/terraform-provider-influxdb#22",
  "orgID": "90a2dbdc3b0ff490",
  "org": "test",
  "userID": "0cdd7d2ab673a000",
  "user": "admin",
  "permissions": [
    { "action": "read", "resource": { "type": "buckets" } },
    { "action": "write", "resource": { "type": "buckets" } }
  ],
  "links": {
    "self": "/api/v2/authorizations/0ce48e112f82f000",
    "user": "/api/v2/users/0cdd7d2ab673a000"
  },
  "createdAt": "2024-04-15T14:48:13.246200754Z",
  "updatedAt": "2024-04-15T14:48:13.246200754Z"
}
```

**Comment by zevisert** [comment]
> The problem now is if you set `name` attribute the influx api does not send the attribute back in the response causing unexpected new value issue in the provider. You can follow the discussion going on [here](https://discuss.hashicorp.com/t/when-applying-changes-to-provider-produced-an-unexpected-new-value-name-was-cty-stringval-but-now-null/65159/3). I will wait for the response from hashicorp and see how to proceed on this.

Maybe that's been fixed? I'm using containerized influx version `docker.io/library/influxdb:2.7.4-alpine`, and I'm getting more fields back in permissions than I'm sending
```http
POST http://localhost:8086/api/v2/authorizations
Cookie: influxdb-oss-session=a6[...]Iw==
content-type: application/json

{
    "orgID": "90a2dbdc3b0ff490",
    "description": "komminarlabs/terraform-provider-influxdb#22 (named)",
    "permissions": [
        {
            "action": "read",
            "resource": {
                "orgID": "90a2dbdc3b0ff490",
                "type": "buckets",
                "id": "e42561946e0fbc6c",
                "name": "telegraf"
            }
        },
        {
            "action": "write",
            "resource": {
                "orgID": "90a2dbdc3b0ff490",
                "type": "buckets",
                "id": "e42561946e0fbc6c",
                "name": "telegraf"
            }
        }
    ]
}

---
HTTP/1.1 201 Created
Content-Type: application/json; charset=utf-8
X-Influxdb-Build: OSS
X-Influxdb-Version: v2.7.4
Date: Mon, 15 Apr 2024 14:55:02 GMT
Content-Length: 920
Connection: close

{
  "id": "0ce48fa0bd42f000",
  "token": "v_m[...]xA==",
  "status": "active",
  "description": "komminarlabs/terraform-provider-influxdb#22 (named)",
  "orgID": "90a2dbdc3b0ff490",
  "org": "test",
  "userID": "0cdd7d2ab673a000",
  "user": "admin",
  "permissions": [
    {
      "action": "read",
      "resource": {
        "type": "buckets",
        "id": "e42561946e0fbc6c",
        "orgID": "90a2dbdc3b0ff490",
        "name": "telegraf",
        "org": "test"
      }
    },
    {
      "action": "write",
      "resource": {
        "type": "buckets",
        "id": "e42561946e0fbc6c",
        "orgID": "90a2dbdc3b0ff490",
        "name": "telegraf",
        "org": "test"
      }
    }
  ],
  "links": {
    "self": "/api/v2/authorizations/0ce48fa0bd42f000",
    "user": "/api/v2/users/0cdd7d2ab673a000"
  },
  "createdAt": "2024-04-15T14:55:02.389518988Z",
  "updatedAt": "2024-04-15T14:55:02.389518988Z"
}
```

**Comment by zevisert** [comment]
> If this is something urgent for you then ofcourse I can set the `name` attribute read-only for now so you can continue with using `id` attribute. Let me know.

If you're comfortable making a release like that, I'd appreciate it. The application I'm working with needs to create all-access tokens, and I can't use this custom resource in pulumi to do that since the permission's `id` is currently marked as required. See https://github.com/komminarlabs/pulumi-influxdb/issues/10

**Review by thulasirajkomminar — APPROVED** [review]

**Comment by thulasirajkomminar** [comment]
@zevisert Made some changes to the schema and docs. The `name` field is `read-only` now, I will spend some time to test the `name` field with more influx versions and release it in a future version. For now, you can use the `id` field together with a data source for specific resource authorization and ignore the `id` field to create all access token.

**Comment by zevisert** [comment]
Thanks @thulasirajkomminar! This is great! Can I do anything to help release this into your pulumi provider as well?

**Comment by thulasirajkomminar** [comment]
> Thanks @thulasirajkomminar! This is great! Can I do anything to help release this into your pulumi provider as well?

It's fairly simple so will try to release a new version today/tomorrow.

**Pull request merged**
